1. 
SELECT NOMPILOTE, ADRESSE 
FROM PILOTE;

2. 
SELECT DISTINCT(VILLEDEP) 
FROM VOL;

3. 
SELECT NUMVOL, NUMPILOTE, NUMAVION, VILLEDEP, VILLEARR, HEUREDEP, HEUREARR 
FROM VOL 
WHERE TIME(HEUREDEP) > TIME('14:00') AND TIME(HEUREDEP) < TIME('16:00');

4. 
SELECT * FROM AVION 
WHERE NOMAVION 
LIKE '%Airbus%';

5. 
SELECT * FROM PILOTE 
WHERE NOMPILOTE 
LIKE '_i%';

6. 
SELECT * FROM AVION 
WHERE CAPACITE 
BETWEEN 200 AND 300;

7. 
SELECT NOMAVION, NUMAVION, LOCALISATION 
FROM AVION 
WHERE CAPACITE > 200 AND LOCALISATION <> 'Nice' 
ORDER BY NUMAVION DESC;

8. 
SELECT DISTINCT NOMPILOTE 
FROM PILOTE 
JOIN VOL ON PILOTE.NUMPILOTE = VOL.NUMPILOTE 
WHERE VILLEDEP = 'Paris';

9. 
SELECT DISTINCT NOMPILOTE 
FROM PILOTE  
JOIN AVION ON PILOTE.ADRESSE = AVION.LOCALISATION 
WHERE AVION.NOMAVION LIKE '%Airbus%'

10. 
SELECT NOMPILOTE
FROM PILOTE
WHERE NUMPILOTE IN (
    SELECT NUMPILOTE
    FROM VOL
    WHERE NUMAVION IN (
        SELECT NUMAVION
        FROM VOL
        WHERE NUMPILOTE = 2
    )
);

11. 
SELECT DISTINCT AVION.NUMAVION, AVION.NOMAVION
FROM VOL
JOIN AVION ON VOL.NUMAVION = AVION.NUMAVION
WHERE VOL.VILLEDEP IN (
    SELECT VILLEDEP 
    FROM VOL 
    WHERE NUMVOL = 'USA050'
) 
AND AVION.CAPACITE BETWEEN 200 AND 300;

12. 
SELECT NUMAVION, NOMAVION, CAPACITE, LOCALISATION
FROM AVION
WHERE CAPACITE > (
    SELECT max(CAPACITE)
    FROM AVION
    WHERE LOCALISATION = 'Nice'
)

13.
SELECT NUMAVION, NOMAVION, CAPACITE, LOCALISATION
FROM AVION
WHERE CAPACITE > (
    SELECT min(CAPACITE)
    FROM AVION
    WHERE LOCALISATION = 'Nice'
)

14.

SELECT DISTINCT NUMPILOTE, NOMPILOTE, ADRESSE 
FROM PILOTE
JOIN AVION ON AVION.LOCALISATION = PILOTE.ADRESSE AND AVION.NOMAVION LIKE '%Airbus%'
WHERE NUMPILOTE IN (
	SELECT NUMPILOTE 
    FROM VOL 
    WHERE VILLEDEP in (
		SELECT VOL.VILLEARR
		FROM VOL 
		JOIN PILOTE ON PILOTE.NUMPILOTE= VOL.NUMPILOTE AND PILOTE.NOMPILOTE LIKE '%Ader%'
        )
    );

16.
SELECT COUNT(DISTINCT NUMPILOTE)
FROM VOL;

